server:
  port: 9000

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
            scope:
              - login:info
          vk:
            client-id: ${VK_CLIENT_ID}
            client-secret: ${VK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/vk"
            scope:
              - email
          mailru:
            client-id: ${MAIL_CLIENT_ID}
            client-secret: ${MAIL_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/mailru"
            scope:
              - userinfo


  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  codec:
    max-in-memory-size: 2MB

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: debug
    org.springframework.web.reactive: off

user:
  service:
    url: http://localhost:8081  # локально user-service в IDE (или http://user-service:8081 в Docker)

jwt:
  secret: "${SECRET_JWT:defaultSecretForLocalTesting}"  # подставляется через ENV, но есть дефолт
  expiration-ms: 3600000          # 1 час
  refresh-expiration-ms: 604800000 # 7 дней

